import { ArrowRight, MessageCircle, TrendingDown, TrendingUp } from 'lucide-react';
import Container from '../../../components/Container';

type ReportRow = { label:string; value:string; change:string; direction?:'up'|'down'; width:string };
type Meaning = { metric:string; meaning:string; decision:string };
type Sector = { title:string; question:string; image:string; problems:string[]; reportTitle:string; reportRows:ReportRow[]; meanings:Meaning[]; outputs:string[]; message:string };

const commonOutputs = [
  'استلام وتنظيم المستندات المالية ومراجعتها',
  'تسجيل ومتابعة الإيرادات والمصروفات أولًا بأول',
  'إعداد ومتابعة القوائم والتقارير المالية',
  'متابعة العملاء والموردين والتحصيل والالتزامات',
  'متابعة الزكاة وضريبة القيمة المضافة والالتزامات ذات الصلة',
  'تنظيم البيانات المالية لتكون جاهزة للمراجعة واتخاذ القرار'
];
const commonProcess = ['تواصل معنا','نحدد المشكلة','نطلب البيانات والمستندات','التقييم الأولي','ربط النظام','بدء التسجيل والمتابعة','التقرير الأول','متابعة يومية'];

const sectors:Record<string,Sector> = {
  'restaurants-cafes': {
    title:'الإدارة المالية للمطاعم والكافيهات', question:'هل تعرف أين يذهب ربح مطعمك؟', image:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=2400&q=85',
    problems:['أشعر أن المبيعات جيدة، لكن المبلغ الذي يتبقى لي في نهاية الشهر أقل مما أتوقع.','لا أستطيع معرفة هل ارتفاع تكلفة الطعام والهدر يأكل من هامش الربح أم لا.','جزء كبير من أموالي موجود في المخزون ولا أعرف ما الذي يتحرك وما الذي يتعطل.','أحتاج أن أعرف ربحية الأصناف أو الفروع بدلًا من النظر إلى إجمالي المبيعات فقط.'], reportTitle:'تقرير مالي مختصر — مثال توضيحي',
    reportRows:[{label:'المبيعات',value:'285,000 ر.س',change:'+8.4%',direction:'up',width:'86%'},{label:'تكلفة الطعام',value:'112,000 ر.س',change:'39.3%',direction:'down',width:'63%'},{label:'المصروفات التشغيلية',value:'84,000 ر.س',change:'+4.1%',direction:'up',width:'47%'},{label:'صافي الربح',value:'89,000 ر.س',change:'31.2%',direction:'up',width:'58%'},{label:'التدفق النقدي',value:'42,000 ر.س',change:'متاح',width:'34%'},{label:'المخزون',value:'67,000 ر.س',change:'يحتاج متابعة',direction:'down',width:'42%'}],
    meanings:[{metric:'تكلفة الطعام 39.3%',meaning:'هذه النسبة تخبرنا كم تستهلك تكلفة المواد من المبيعات.',decision:'مراجعة الشراء والوصفات والحصص والهدر والتسعير.'},{metric:'المخزون 67K',meaning:'جزء من رأس المال موجود في مخزون وليس نقدًا متاحًا.',decision:'ضبط دورة الشراء ومتابعة الأصناف البطيئة.'},{metric:'التدفق 42K',meaning:'الربح المحاسبي لا يعني أن النقد المتاح يساويه.',decision:'ترتيب المصروفات والالتزامات حسب السيولة الفعلية.'}],
    outputs:commonOutputs.concat(['تحليل تكلفة الطعام والهدر','تحليل ربحية الأصناف والفروع','تقرير السيولة والمخزون']), message:'السلام عليكم، أريد معرفة الوضع المالي الحقيقي لمطعمي والمؤشرات التي يجب متابعتها.'
  },
  contracting: {
    title:'الإدارة المالية لقطاع المقاولات', question:'هل تعرف ربحية مشروعك قبل أن ينتهي؟', image:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=2400&q=85',
    problems:['أريد أن أعرف تكلفة كل مشروع فعلية، وليس مجرد إجمالي المصروفات.','أخشى أن تزيد تكلفة مشروع قبل أن أكتشف أنها قللت هامش الربح.','المستخلصات والتحصيل والالتزامات تجعلني غير متأكد من السيولة المتاحة.','أحتاج أن أعرف هل نسبة الإنجاز الحالية متناسبة مع ما صُرف وما تم تحصيله.'], reportTitle:'تقرير المشروع المالي — مثال توضيحي',
    reportRows:[{label:'قيمة العقود',value:'1.80M ر.س',change:'إجمالي',width:'92%'},{label:'التكلفة المنفذة',value:'1.02M ر.س',change:'56.7%',direction:'up',width:'57%'},{label:'نسبة الإنجاز',value:'62%',change:'مقابل التكلفة',width:'62%'},{label:'الربحية المتوقعة',value:'18.4%',change:'مستهدف',direction:'up',width:'49%'},{label:'المستحق للتحصيل',value:'265K ر.س',change:'ضغط سيولة',direction:'down',width:'39%'},{label:'انحراف التكلفة',value:'+7.2%',change:'يحتاج تدخلًا',direction:'up',width:'28%'}],
    meanings:[{metric:'انحراف التكلفة +7.2%',meaning:'التكلفة ترتفع أسرع من الخطة، وهذا قد يخفض هامش المشروع.',decision:'تحديد مصدر الانحراف وإعادة تقدير الربحية.'},{metric:'إنجاز 62%',meaning:'نسبة الإنجاز وحدها لا تكفي دون ربطها بالتكلفة والإيراد.',decision:'مقارنة الإنجاز بالتكلفة والمستخلصات والتحصيل.'},{metric:'تحصيل 265K',meaning:'المشروع قد يكون مربحًا على الورق لكن السيولة متأخرة.',decision:'ترتيب التحصيل والالتزامات حسب الأولوية.'}],
    outputs:commonOutputs.concat(['ربحية كل مشروع','تقرير تكلفة مقابل الإنجاز','متابعة المستخلصات والتحصيل','كشف مبكر لانحرافات التكلفة']), message:'السلام عليكم، أريد معرفة ربحية مشاريعي والتكاليف والسيولة بشكل واضح.'
  },
  'trade-retail': {
    title:'الإدارة المالية للتجارة والتجزئة', question:'هل المبيعات المرتفعة تتحول فعلًا إلى ربح؟', image:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=2400&q=85',
    problems:['أرى مبيعات مرتفعة، لكنني لا أعرف الهامش الحقيقي بعد تكلفة الشراء والمصروفات.','أموال كثيرة مرتبطة في المخزون وأحتاج أن أعرف أين تتجمد السيولة.','تغير أسعار الشراء يضغط على الربح وأحتاج رؤية ذلك بسرعة.','أريد معرفة المنتجات أو الفروع التي تحقق لي ربحًا حقيقيًا.'], reportTitle:'تقرير المبيعات والربحية — مثال توضيحي',
    reportRows:[{label:'المبيعات',value:'420K ر.س',change:'+12.5%',direction:'up',width:'90%'},{label:'تكلفة المبيعات',value:'276K ر.س',change:'65.7%',direction:'down',width:'66%'},{label:'هامش الربح',value:'34.3%',change:'تحت المتابعة',width:'43%'},{label:'المخزون',value:'310K ر.س',change:'مرتفع',direction:'down',width:'72%'},{label:'أصناف بطيئة',value:'14%',change:'تحتاج قرارًا',direction:'down',width:'28%'},{label:'صافي الربح',value:'62K ر.س',change:'14.8%',direction:'up',width:'34%'}],
    meanings:[{metric:'الهامش 34.3%',meaning:'المبيعات وحدها لا تكشف جودة الربح.',decision:'مراجعة تسعير المنتجات وتكلفة الشراء.'},{metric:'المخزون 310K',meaning:'رأس مال كبير مرتبط ببضاعة لم تتحول بعد إلى نقد.',decision:'تحديد البطيء وربط الشراء بالدوران.'},{metric:'أصناف بطيئة 14%',meaning:'السيولة معرضة للتجميد أو الخصم أو التلف.',decision:'تحديد الأصناف التي تحتاج تصرفًا سريعًا.'}],
    outputs:commonOutputs.concat(['تحليل هامش المنتجات والفروع','تقرير المخزون والدوران','مؤشرات تدعم قرارات الشراء والتسعير']), message:'السلام عليكم، أريد تحليل مبيعاتي ومخزوني وهامش الربح لاتخاذ قرارات أفضل.'
  },
  'pharmacies-health': {
    title:'الإدارة المالية للصيدليات والمنشآت الصحية', question:'هل تعرف أي جزء من نشاطك يحقق الربح فعلًا؟', image:'https://images.unsplash.com/photo-1580281658223-9b93f18ae9ae?auto=format&fit=crop&w=2400&q=85',
    problems:['المبيعات موجودة، لكنني أحتاج أن أعرف ما يتبقى لي فعلًا بعد تكلفة المنتجات والمصروفات.','المخزون والأصناف بطيئة الحركة تربط جزءًا من السيولة.','الخصومات وتغير تكلفة الشراء قد تضغط على هامش الربح.','أحتاج أن أعرف أثر المصروفات على ربحية النشاط بوضوح.'], reportTitle:'تقرير مالي للنشاط الصحي — مثال توضيحي',
    reportRows:[{label:'المبيعات',value:'360K ر.س',change:'+6.8%',direction:'up',width:'82%'},{label:'تكلفة المبيعات',value:'258K ر.س',change:'71.7%',direction:'down',width:'72%'},{label:'الهامش',value:'28.3%',change:'تحت المتابعة',width:'37%'},{label:'المخزون',value:'195K ر.س',change:'مرتفع',direction:'down',width:'61%'},{label:'مصروفات التشغيل',value:'54K ر.س',change:'+3.2%',direction:'up',width:'31%'},{label:'صافي الربح',value:'48K ر.س',change:'13.3%',direction:'up',width:'27%'}],
    meanings:[{metric:'الهامش 28.3%',meaning:'ارتفاع المبيعات مع انخفاض الهامش قد لا يحسن الربح.',decision:'تحليل تكلفة الشراء والخصومات وربحية الأصناف.'},{metric:'المخزون 195K',meaning:'السيولة قد تكون مرتبطة بأصناف لا تتحرك بالسرعة المطلوبة.',decision:'متابعة الدوران والأصناف البطيئة.'},{metric:'المصروفات 54K',meaning:'زيادة المصروفات تقلل ما يتبقى من الهامش.',decision:'مقارنة المصروفات بالعائد والأثر على الربحية.'}],
    outputs:commonOutputs.concat(['تحليل الهامش والتكلفة','تقرير المخزون والدوران','مؤشرات تساعد على ضبط التسعير والشراء']), message:'السلام عليكم، أريد معرفة ربحية نشاطي الصحي ومؤشرات المخزون والسيولة.'
  },
  'services-professions': {
    title:'الإدارة المالية للخدمات والمهن', question:'هل تعرف تكلفة الخدمة التي تقدمها وربحيتها؟', image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2400&q=85',
    problems:['الإيرادات موجودة لكن تكلفة تقديم الخدمة غير واضحة لي.','المصروفات الثابتة والمتغيرة تقلل الربحية وأحتاج متابعة أثرها.','أريد معرفة الخدمات أو العملاء الأكثر ربحية.','التحصيل قد يتأخر رغم تسجيل الإيراد، وهذا يؤثر على السيولة.'], reportTitle:'تقرير ربحية الخدمات — مثال توضيحي',
    reportRows:[{label:'الإيرادات',value:'240K ر.س',change:'+10.2%',direction:'up',width:'78%'},{label:'تكلفة تقديم الخدمة',value:'92K ر.س',change:'38.3%',direction:'down',width:'39%'},{label:'المصروفات',value:'71K ر.س',change:'+5.6%',direction:'up',width:'30%'},{label:'هامش التشغيل',value:'32.1%',change:'تحت المتابعة',width:'45%'},{label:'المستحق للتحصيل',value:'58K ر.س',change:'متأخر',direction:'down',width:'24%'},{label:'صافي الربح',value:'77K ر.س',change:'32.1%',direction:'up',width:'31%'}],
    meanings:[{metric:'تكلفة الخدمة 38.3%',meaning:'ارتفاع التكلفة قد يعني أن بعض الخدمات لا تحقق الهامش المتوقع.',decision:'حساب ربحية كل خدمة ومراجعة التسعير والتكلفة.'},{metric:'تحصيل 58K',meaning:'الإيراد المسجل لا يعني بالضرورة نقدية متاحة.',decision:'ترتيب التحصيل وربطه بالالتزامات.'},{metric:'هامش التشغيل 32.1%',meaning:'المهم ليس حجم الإيراد فقط بل ما يتبقى بعد تكلفة التشغيل.',decision:'تركيز النمو على الخدمات والعملاء الأكثر ربحية.'}],
    outputs:commonOutputs.concat(['تحليل ربحية الخدمات','تقرير الإيرادات والتحصيل','مؤشرات تساعد على التسعير']), message:'السلام عليكم، أريد معرفة ربحية خدماتي وتكلفة التشغيل والتحصيل.'
  },
  'startups-growing': {
    title:'الإدارة المالية للشركات الناشئة والمتنامية', question:'كم لديك من الوقت قبل أن تحتاج إلى تمويل جديد؟', image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=2400&q=85',
    problems:['النمو يحدث لكن الصورة المالية لا تواكب سرعة قراراتي.','المصروفات ترتفع ولا أملك رؤية واضحة لمعدل الحرق.','أحتاج أن أعرف مدة بقاء السيولة المتاحة.','قرارات التوسع والتوظيف والتمويل تحتاج أرقامًا أدق.'], reportTitle:'تقرير السيولة والنمو — مثال توضيحي',
    reportRows:[{label:'الإيرادات الشهرية',value:'180K ر.س',change:'+18.6%',direction:'up',width:'72%'},{label:'المصروفات الشهرية',value:'145K ر.س',change:'+11.4%',direction:'up',width:'58%'},{label:'صافي التدفق',value:'+35K ر.س',change:'موجب',direction:'up',width:'36%'},{label:'السيولة المتاحة',value:'620K ر.س',change:'مثال',width:'82%'},{label:'معدل الحرق',value:'0 ر.س',change:'بحسب المثال',width:'18%'},{label:'نقطة التعادل',value:'≈ 150K',change:'إيراد شهري',width:'51%'}],
    meanings:[{metric:'الإيرادات 180K',meaning:'النمو يصبح أكثر أمانًا عندما تعرف تكلفته وأثره على النقدية.',decision:'ربط النمو بالمصروفات والهامش والتدفق النقدي.'},{metric:'المصروفات 145K',meaning:'زيادة الإنفاق قبل فهم أثره قد تسرع استهلاك السيولة.',decision:'تحديد المصروفات التي تدعم النمو وتلك التي يمكن ضبطها.'},{metric:'نقطة التعادل 150K',meaning:'رقم واضح لما يجب تحقيقه شهريًا لتغطية التكاليف.',decision:'متابعة الاقتراب من التعادل قبل قرارات التوسع.'}],
    outputs:commonOutputs.concat(['تقرير التدفق النقدي','متابعة المصروفات ومعدل الحرق','نقطة التعادل ومؤشرات النمو']), message:'السلام عليكم، أريد معرفة وضع السيولة والنمو ومعدل الحرق ونقطة التعادل لشركتي.'
  }
};

const whatsappUrl=(message:string)=>`https://wa.me/966511294383?text=${encodeURIComponent(message)}`;

function ContractingPage({sector}:{sector:S​ector}) {
  return <main dir="rtl" className="bg-white text-slate-900">
    <section className="border-b border-slate-200 bg-white"><Container className="py-4 md:py-6 lg:py-8"><a href="/#sectors-section-wrapper" className="mb-3 inline-flex items-center gap-2 text-[11px] text-slate-500 md:text-sm"><ArrowRight className="h-4 w-4"/> العودة إلى القطاعات</a><div className="grid items-center gap-5 lg:grid-cols-[1.35fr_0.65fr]"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">قطاع المقاولات</p><h1 className="mt-1 text-2xl font-extrabold leading-tight md:text-4xl lg:text-5xl">هل تعرف ربحية مشروعك قبل أن ينتهي؟</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 md:text-lg md:leading-8">في المقاولات، لا تكفي معرفة إجمالي الإيرادات والمصروفات. المهم أن تعرف تكلفة كل مشروع، نسبة إنجازه، ربحه المتوقع، مستحقاتك والتزاماتك، وماذا يحدث للسيولة.</p><p className="mt-3 text-sm font-semibold leading-6 text-slate-900 md:text-base md:leading-7">دوري كمحاسب مالي هو تحويل العمليات المالية للمشاريع إلى معلومات واضحة تساعدك على معرفة وضع كل مشروع واتخاذ القرار في الوقت المناسب.</p></div><img src={sector.image} alt={sector.title} className="h-40 w-full rounded-xl object-cover md:h-52 lg:h-64"/></div></Container></section>

    <Container className="py-5 md:py-7 lg:py-9">
      <section className="border-b border-slate-200 pb-5 md:pb-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">ما الذي يهمك كصاحب شركة؟</p><h2 className="mt-1 text-xl font-bold md:text-3xl">المشروع هو نقطة البداية</h2></div><p className="hidden max-w-xl text-left text-sm leading-6 text-slate-500 md:block">نربط الإيراد والتكلفة والإنجاز والمستخلصات والتحصيل والالتزامات بالمشروع نفسه، بدل النظر إلى أرقام إجمالية لا توضح أين الربح وأين المشكلة.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="border-r-2 border-emerald-500 pr-3"><strong className="text-sm md:text-base">تكلفة المشروع</strong><p className="mt-1 text-xs leading-5 text-slate-600 md:text-sm">مواد، عمالة، مقاولون، معدات ومصاريف مرتبطة بالمشروع.</p></div><div className="border-r-2 border-emerald-500 pr-3"><strong className="text-sm md:text-base">الإنجاز والربحية</strong><p className="mt-1 text-xs leading-5 text-slate-600 md:text-sm">نسبة الإنجاز والتكلفة الفعلية والربح المتوقع والانحراف عن الميزانية.</p></div><div className="border-r-2 border-emerald-500 pr-3"><strong className="text-sm md:text-base">المستخلصات والتحصيل</strong><p className="mt-1 text-xs leading-5 text-slate-600 md:text-sm">المعتمد، المحصل، المحتجز، الدفعات المقدمة والمبالغ المستحقة.</p></div><div className="border-r-2 border-emerald-500 pr-3"><strong className="text-sm md:text-base">السيولة والالتزامات</strong><p className="mt-1 text-xs leading-5 text-slate-600 md:text-sm">ما لديك نقدًا، ما لك، ما عليك، وما تحتاجه المشاريع خلال الفترة القادمة.</p></div></div></section>

      <section className="border-b border-slate-200 py-5 md:py-7"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">مثال توضيحي</p><h2 className="mt-1 text-xl font-bold md:text-3xl">تقرير مالي مختصر لمشروع</h2><p className="mt-1 text-[11px] text-slate-500 md:text-sm">الأرقام نموذج بصري وليست بيانات منشأة فعلية.</p></div><span className="text-[11px] text-slate-400 md:text-sm">التكلفة · الإنجاز · الربحية · التحصيل</span></div><div className="mt-4 overflow-hidden border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-2 gap-px bg-slate-200 md:grid-cols-4"><div className="bg-white p-3 md:p-4"><span className="text-[11px] text-slate-500 md:text-xs">قيمة العقد</span><strong className="mt-1 block text-lg md:text-2xl">4.80M</strong><small className="text-[10px] text-slate-400">ر.س</small></div><div className="bg-white p-3 md:p-4"><span className="text-[11px] text-slate-500 md:text-xs">نسبة الإنجاز</span><strong className="mt-1 block text-lg md:text-2xl">68%</strong><div className="mt-2 h-1.5 bg-slate-100"><span className="block h-full w-[68%] bg-emerald-500"/></div></div><div className="bg-white p-3 md:p-4"><span className="text-[11px] text-slate-500 md:text-xs">التكلفة حتى تاريخه</span><strong className="mt-1 block text-lg md:text-2xl">2.90M</strong><small className="text-[10px] text-slate-400">ر.س</small></div><div className="bg-white p-3 md:p-4"><span className="text-[11px] text-slate-500 md:text-xs">الهامش الحالي</span><strong className="mt-1 block text-lg text-emerald-700 md:text-2xl">12%</strong><small className="text-[10px] text-slate-400">تحت المتابعة</small></div></div><div className="grid gap-0 md:grid-cols-2"><div className="border-t border-slate-200 p-3 md:p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold md:text-sm">الإيراد حتى تاريخه</span><strong className="text-sm md:text-base">3.30M ر.س</strong></div><div className="mt-2 h-2 bg-slate-100"><span className="block h-full w-[69%] bg-emerald-500"/></div></div><div className="border-t border-slate-200 p-3 md:p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold md:text-sm">المستحق لدى العميل</span><strong className="text-sm md:text-base">620K ر.س</strong></div><div className="mt-2 h-2 bg-slate-100"><span className="block h-full w-[42%] bg-amber-400"/></div></div></div></div></section>

      <section className="border-b border-slate-200 py-5 md:py-7"><div className="grid gap-5 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">من الرقم إلى القرار</p><h2 className="mt-1 text-xl font-bold md:text-3xl">ماذا تعني الأرقام لك؟</h2><p className="mt-2 text-sm leading-6 text-slate-600 md:text-base md:leading-7">التقرير لا يكتفي بإظهار الرقم. المهم أن تعرف لماذا تغير، وما أثره على المشروع، وما الذي يحتاج إلى متابعة.</p></div><div className="divide-y divide-slate-200 border-y border-slate-200"><div className="grid gap-1 py-3 md:grid-cols-[150px_1fr]"><strong className="text-sm md:text-base">ارتفاع التكلفة</strong><p className="text-xs leading-5 text-slate-600 md:text-sm md:leading-6">نحدد مصدر الزيادة: مواد، عمالة، مقاول باطن، معدات أو مصروفات أخرى، ثم نعيد تقدير أثرها على الربحية.</p></div><div className="grid gap-1 py-3 md:grid-cols-[150px_1fr]"><strong className="text-sm md:text-base">تأخر التحصيل</strong><p className="text-xs leading-5 text-slate-600 md:text-sm md:leading-6">نوضح ما لك عند العملاء، أعمار الديون، المحتجزات والمبالغ التي تؤثر على السيولة القادمة.</p></div><div className="grid gap-1 py-3 md:grid-cols-[150px_1fr]"><strong className="text-sm md:text-base">انخفاض الهامش</strong><p className="text-xs leading-5 text-slate-600 md:text-sm md:leading-6">نقارن الإيراد والتكلفة والإنجاز والميزانية لمعرفة أين حدث الانحراف قبل أن يتسع.</p></div></div></div></section>

      <section className="border-b border-slate-200 py-5 md:py-7"><div className="grid gap-4 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">ما الذي يدخل في العمل؟</p><h2 className="mt-1 text-xl font-bold md:text-3xl">من المستند إلى القوائم المالية</h2><p className="mt-2 text-sm leading-6 text-slate-600 md:text-base md:leading-7">لا نركز على المشروع وحده؛ نرتب المنظومة المالية التي يعتمد عليها القرار.</p></div><div className="grid grid-cols-2 gap-x-5 gap-y-3 md:grid-cols-3"><div><strong className="text-sm md:text-base">المستندات</strong><p className="text-xs leading-5 text-slate-600">استلام وتنظيم ومراجعة البيانات والمستندات.</p></div><div><strong className="text-sm md:text-base">الإيرادات والمصروفات</strong><p className="text-xs leading-5 text-slate-600">تسجيل ومتابعة العمليات وربطها بالحسابات والمشاريع.</p></div><div><strong className="text-sm md:text-base">العملاء والموردون</strong><p className="text-xs leading-5 text-slate-600">الأرصدة، التحصيل، الدفعات والمستحقات.</p></div><div><strong className="text-sm md:text-base">الإقفال والتسويات</strong><p className="text-xs leading-5 text-slate-600">البنوك، المصروفات والإيرادات المستحقة، الإهلاك وغيرها حسب الحاجة.</p></div><div><strong className="text-sm md:text-base">القوائم والتقارير</strong><p className="text-xs leading-5 text-slate-600">المركز المالي، الدخل، التدفقات النقدية والتقارير الإدارية.</p></div><div><strong className="text-sm md:text-base">الزكاة والضريبة</strong><p className="text-xs leading-5 text-slate-600">تجهيز ومتابعة البيانات اللازمة للالتزامات ذات الصلة ضمن نطاق العمل.</p></div></div></div></section>

      <section className="border-b border-slate-200 py-5 md:py-7"><div className="grid gap-4 md:grid-cols-2"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">الرقابة</p><h2 className="mt-1 text-xl font-bold md:text-3xl">حتى لا تختلط أرقام المشاريع</h2><p className="mt-2 text-sm leading-6 text-slate-600 md:text-base md:leading-7">تتم متابعة تحميل التكاليف على المشروع الصحيح، والمشتريات وصرف المواد، والمصروفات غير المبررة أو غير المعتمدة، مع متابعة الموردين والمقاولين والمعدات حسب طبيعة النشاط.</p></div><div className="border-r-2 border-emerald-500 pr-4"><p className="text-sm font-semibold md:text-base">ما نبحث عنه في التحليل</p><p className="mt-2 text-sm leading-6 text-slate-600">لماذا ارتفعت التكلفة؟ لماذا انخفض الهامش؟ لماذا تأخر التحصيل؟ لماذا استهلاك المواد أعلى من المتوقع؟ وأين يحدث التسرب المالي؟</p></div></div></section>

      <section className="border-b border-slate-200 py-5 md:py-7"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">ماذا تحصل عليه؟</p><h2 className="mt-1 text-xl font-bold md:text-3xl">صورة مالية قابلة للاستخدام</h2></div><p className="hidden max-w-xl text-sm leading-6 text-slate-500 md:block">الهدف أن تكون الأرقام منظمة ومفهومة وجاهزة للمراجعة واتخاذ القرار.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div className="bg-slate-50 p-3 md:p-4"><strong className="text-sm md:text-base">ربحية كل مشروع</strong><p className="mt-1 text-xs leading-5 text-slate-600">الإيراد والتكلفة والإنجاز والهامش المتوقع.</p></div><div className="bg-slate-50 p-3 md:p-4"><strong className="text-sm md:text-base">المستخلصات والتحصيل</strong><p className="mt-1 text-xs leading-5 text-slate-600">المعتمد، المحصل، المحتجز وما تبقى.</p></div><div className="bg-slate-50 p-3 md:p-4"><strong className="text-sm md:text-base">السيولة والتدفقات</strong><p className="mt-1 text-xs leading-5 text-slate-600">النقد المتاح والاحتياجات والالتزامات القادمة.</p></div><div className="bg-slate-50 p-3 md:p-4"><strong className="text-sm md:text-base">القوائم والتقارير</strong><p className="mt-1 text-xs leading-5 text-slate-600">تقارير مالية وإدارية تدعم قرار الإدارة.</p></div></div></section>

      <section className="border-b border-slate-200 py-5 md:py-7"><div className="grid gap-4 lg:grid-cols-[0.65fr_1.35fr]"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">كيف نبدأ؟</p><h2 className="mt-1 text-xl font-bold md:text-3xl">خطوات واضحة من أول تواصل</h2><p className="mt-2 text-sm leading-6 text-slate-600">نحدد لاحقًا الطريقة التي تناسب نشاطك وحجم العمل والمستندات والأنظمة المتاحة.</p></div><div className="grid grid-cols-2 gap-x-4 gap-y-3 md:grid-cols-4">{commonProcess.map((step,i)=><div key={step}><span className="text-[10px] font-bold text-emerald-700 md:text-xs">{String(i+1).padStart(2,'0')}</span><p className="mt-0.5 text-xs font-medium text-slate-700 md:text-sm">{step}</p></div>)}</div></div></section>

      <section className="py-5 md:py-7"><div className="border-t-2 border-slate-900 pt-4 md:flex md:items-center md:justify-between md:gap-8"><div><p className="text-xs font-semibold text-emerald-700 md:text-sm">لماذا القائد؟</p><h2 className="mt-1 text-xl font-bold md:text-3xl">الأرقام ليست للتسجيل فقط — هي أساس القرار.</h2><p className="mt-1 text-sm leading-6 text-slate-600 md:text-base">تنظيم الأرقام وتحويلها إلى صورة مالية واضحة تساعدك على معرفة وضع منشأتك واتخاذ القرار المناسب.</p><p className="mt-2 text-xs leading-5 text-slate-500 md:text-sm">نتعامل مع مستندات وبيانات النشاط ضمن نطاق العمل المتفق عليه، مع تنظيمها وحفظها بطريقة تسهّل الرجوع إليها.</p></div><a href={whatsappUrl(sector.message)} target="_blank" rel="noreferrer" className="mt-4 inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-5 py-3 text-sm font-bold text-white hover:bg-emerald-700 md:mt-0 md:text-base"><MessageCircle className="h-4 w-4"/> ناقش وضع شركتك</a></div></section>
    </Container>
  </main>;
}

export default function SectorDetailPage({slug}:{slug:string}) {
  const sector=sectors[slug];
  if(!sector) return <main dir="rtl" className="min-h-screen py-12 text-center"><Container><h1 className="text-2xl font-bold">القطاع غير موجود</h1><a href="/" className="mt-3 inline-flex items-center gap-2 text-emerald-700"><ArrowRight className="h-4 w-4"/> العودة للرئيسية</a></Container></main>;
  if(slug==='contracting') return <ContractingPage sector={sector}/>;
  return <main dir="rtl" className="bg-white text-slate-900">
    <section className="bg-slate-950 text-white"><Container className="py-4 md:py-5"><a href="/#sectors-section-wrapper" className="mb-2 inline-flex items-center gap-2 text-[11px] text-slate-300"><ArrowRight className="h-4 w-4"/> العودة إلى القطاعات</a><div className="grid items-center gap-3 lg:grid-cols-[1fr_260px]"><div><h1 className="text-xl font-extrabold leading-tight md:text-4xl">{sector.question}</h1><p className="mt-1 text-xs text-slate-300 md:text-sm">{sector.title}</p></div><img src={sector.image} alt={sector.title} className="h-24 w-full rounded-lg object-cover"/></div></Container></section>
    <Container className="py-4 md:py-5">
      <section className="border-b border-slate-200 pb-4"><h2 className="text-base font-bold md:text-xl">المشاكل التي قد تواجه نشاطك</h2><div className="mt-2 grid gap-x-6 gap-y-0.5 md:grid-cols-2">{sector.problems.map(p=><p key={p} className="text-sm leading-5 text-slate-600 md:text-base md:leading-6">{p}</p>)}</div></section>
      <section className="border-b border-slate-200 py-4"><div className="flex flex-wrap items-end justify-between gap-1"><div><h2 className="text-base font-bold md:text-xl">{sector.reportTitle}</h2><p className="mt-0.5 text-[10px] text-slate-500 md:text-xs">الأرقام نموذج بصري وليست بيانات منشأة فعلية.</p></div><span className="text-[10px] text-slate-400 md:text-xs">المبيعات · التكلفة · الربحية · السيولة</span></div><div className="mt-2 overflow-hidden border-y border-slate-200"><div className="grid grid-cols-[1.35fr_1fr_80px] bg-slate-50 px-2 py-1.5 text-[10px] font-semibold text-slate-500 md:text-xs"><span>المؤشر</span><span>المستوى</span><span>التغير</span></div>{sector.reportRows.map((row,i)=><div key={row.label} className={`grid grid-cols-[1.35fr_1fr_80px] items-center gap-2 px-2 py-2 ${i<sector.reportRows.length-1?'border-b border-slate-100':''}`}><span className="text-xs font-medium text-slate-700 md:text-sm">{row.label}</span><div className="flex items-center justify-between gap-1"><strong className="text-xs text-slate-950 md:text-sm">{row.value}</strong><span className="h-1 w-12 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-emerald-500" style={{width:row.width}}/></span></div><span className={`flex items-center gap-0.5 text-[10px] ${row.direction==='down'?'text-amber-600':row.direction==='up'?'text-emerald-700':'text-slate-500'} md:text-xs`}>{row.direction==='down'?<TrendingDown className="h-3 w-3"/>:row.direction==='up'?<TrendingUp className="h-3 w-3"/>:null}{row.change}</span></div>)}</div></section>
      <section className="border-b border-slate-200 py-4"><h2 className="text-base font-bold md:text-xl">ماذا تعني الأرقام؟</h2><div className="mt-2 divide-y divide-slate-200 border-y border-slate-200">{sector.meanings.map(item=><div key={item.metric} className="grid gap-1 py-2.5 md:grid-cols-[190px_1fr_1fr] md:gap-4"><strong className="text-xs md:text-sm">{item.metric}</strong><p className="text-xs leading-5 text-slate-600 md:text-sm md:leading-6">{item.meaning}</p><p className="text-xs font-semibold leading-5 text-emerald-800 md:text-sm md:leading-6">القرار: {item.decision}</p></div>)}</div></section>
      <section className="border-b border-slate-200 py-4"><div className="grid gap-2 md:grid-cols-[1fr_2fr]"><div><h2 className="text-base font-bold md:text-xl">ماذا ستحصل عليه؟</h2><p className="mt-0.5 text-xs leading-5 text-slate-500 md:text-sm md:leading-6">تقارير وبيانات منظمة تساعدك على رؤية الوضع واتخاذ الخطوة التالية.</p></div><div className="grid gap-x-6 gap-y-0.5 md:grid-cols-2">{sector.outputs.map(o=><p key={o} className="text-xs leading-5 text-slate-700 md:text-sm md:leading-6">{o}</p>)}</div></div></section>
      <section className="border-b border-slate-200 py-4"><h2 className="text-base font-bold md:text-xl">كيف نعمل؟</h2><div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 md:grid-cols-4">{commonProcess.map((step,i)=><div key={step} className="flex items-start gap-1.5"><span className="text-[10px] font-bold text-emerald-700 md:text-xs">{String(i+1).padStart(2,'0')}</span><span className="text-xs text-slate-600 md:text-sm">{step}</span></div>)}</div><p className="mt-2 text-[11px] text-slate-500 md:text-sm">وسوف نحدد لاحقًا الطريقة التي تناسب نشاطك وحجم العمل والمستندات والأنظمة المتاحة.</p></section>
      <section className="py-4"><div className="flex flex-col items-start justify-between gap-3 rounded-lg bg-slate-950 px-4 py-4 text-white md:flex-row md:items-center"><div><p className="text-xs text-emerald-300 md:text-sm">لماذا القائد؟</p><h2 className="mt-0.5 text-base font-bold md:text-xl">الأرقام ليست للتسجيل فقط — هي أساس القرار.</h2><p className="mt-0.5 text-xs text-slate-300 md:text-sm md:leading-6">تنظيم الأرقام وتحويلها إلى صورة مالية واضحة تساعدك على معرفة وضع منشأتك واتخاذ القرار المناسب.</p></div><a href={whatsappUrl(sector.message)} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-1.5 rounded-lg bg-emerald-500 px-4 py-2 text-xs font-bold text-white hover:bg-emerald-400 md:text-sm"><MessageCircle className="h-3.5 w-3.5"/> ناقش وضع منشأتك</a></div></section>
    </Container>
  </main>;
}
